blog_on_rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', {to: 'home#index', as: 'root'}

  get '/posts', {to: redirect('/')}
  resources :posts, except: [:index]

  resources :posts do
    resources :comments
  end

  resources :users, only: [:new, :create, :edit, :update]
  get '/users/:id/edit_password', {to: 'users#edit_password', as: "edit_password"}

  resource :session, only: [:new, :create, :destroy]
end

blog_on_rails/app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    belongs_to :user
    
    validates :title, presence: true, uniqueness: true
    validates :body, presence: true, length: {minimum: 50}
end

blog_on_rails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post_id, except: [:new, :create, :index]
    before_action :authenticate!, except: [:show, :index]
    before_action :authorize!, only: [:destroy, :edit, :update]

    def new
        @post = Post.new
    end

    def create
        @post = Post.new post_params
        @post.user = current_user
        if @post.save
            redirect_to post_path(@post.id), notice: "Post Saved!"
        else
            render :new
        end
    end

    def show
        # @post = Post.find_by_id params[:id]
        @comment = Comment.new
        @comments = @post.comments.order(updated_at: :desc)
    end

    def index
        @post = Post.all.order(updated_at: :desc)
    end

    def destroy
        # @post = Post.find params[:id]
        @post.destroy
        redirect_to posts_path
    end

    def edit
        # @post = Post.find_by_id params[:id]
    end

    def update
        # @post = Post.find params[:id]
        if @post.update post_params
            redirect_to post_path
        else
            render :edit
        end
    end

    private

    def post_params
        params.require(:post).permit(:title, :body)
    end

    def find_post_id
        @post = Post.find params[:id]
    end

    def authorize!
        redirect_to root_path, alert: "Not Authorized" unless can?(:crud, @post)
    end
end

blog_on_rails/app/helpers/posts_helper.rb
module PostsHelper
end

blog_on_rails/app/views/posts/_form.html.erb
<% if @post.errors.any? %>
    <div>
        <% @post.errors.full_messages.each do |msg| %>
            <p class="message"><%=msg%><p>
        <% end %>
    </div>
<% end %>


<%= form_with model: @post, local: true do |form| %>
    <div>
        <%= form.label :title%>
        <%= form.text_field :title%>
    </div>
    <div>
        <%= form.label :body%>
        <%= form.text_area :body%>
    </div>
    <div class="button"><%= form.submit class: "btn btn-primary" %></div>
<% end %>

blog_on_rails/app/views/posts/edit.html.erb
<%= render "form"%>

blog_on_rails/app/views/posts/new.html.erb
<%= render "form"%>

blog_on_rails/app/views/posts/show.html.erb
<h1><%= @post.title%></h1>
<p><%= @post.body %></p>
<div>
    <small><%= time_ago_in_words(@post.updated_at)%></small>
    <br/>
    <small>Posted by: <%= @post.user.name%></small>
    <div class="button">
        <%= link_to "Delete", post_path(@post.id), class: "btn btn-primary", method: :delete, data: {confirm: "Are you sure you want to delete the post?"}%>
        <%= link_to "Edit", edit_post_path(@post), class: "btn btn-primary" %>
    </div>
</div>


<div class="comment-input">
    <h1>Comments</h1>
    <%= form_with model: [@post, @comment], local:true do |form| %>

        <% if @comment.errors.any? %>
            <p><% @comment.errors.full_messages.join(",")%></p>
        <% end %>

        <div>
            <%= form.label :body %>
            <%= form.text_area :body%>
        </div>
        <div class="button"><%= form.submit class: "btn btn-primary" %></div>
    <% end %>
</div>

<% @comments.each do |comment| %>
    <div class="comment">
        <p class="comment-body"><%= comment.body %><p>
        <small>Commented <%= time_ago_in_words(comment.updated_at)%> by <%= comment.user.name%></small> •
        <%= link_to "Delete", post_comment_path(comment.post_id, comment.id), method: :delete, data: {confirm: "Are you sure you want to delete your comment?"} %>
    </div>
<% end %>